apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - ../../base
  - ../../secrets/backend-sealedsecret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml