apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
  - ../../base
  - backend-sealedsecret.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: ghcr.io/khuoo4603/my-graduation-manager-backend
    newTag: sha-51b5eab