spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/gradmanager
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

app:
  dev-token:
    enabled: true
    default-department-id: 1
  storage:
    root: /tmp/gradmanager_local_storage
  jwt:
    secret: "kK0PP8dHYQ30llX7KnFS58DvIcmIN4kVSMxsJdD32gY="
    exp-seconds: 86400

springdoc:
  swagger-ui:
    persistAuthorization: true